{
    "total_results": 5,
    "messages": [
        [
            {
                "id": "901731077872312342",
                "type": 0,
                "content": "I ran into that, not sure exactly how I fixed it but it took a bunch of reinstalling \ud83d\ude2c",
                "channel_id": "889584618372734977",
                "author": {
                    "id": "326107472098099201",
                    "username": "Tom Linton",
                    "avatar": "3073b6377f58d2a64e83b0cb82f445c3",
                    "avatar_decoration": null,
                    "discriminator": "2464",
                    "public_flags": 0
                },
                "attachments": [],
                "embeds": [],
                "mentions": [],
                "mention_roles": [],
                "pinned": false,
                "mention_everyone": false,
                "tts": false,
                "timestamp": "2021-10-24T07:17:22.318000+00:00",
                "edited_timestamp": null,
                "flags": 0,
                "components": [],
                "hit": true
            }
        ],
        [
            {
                "id": "901638073887096842",
                "type": 0,
                "content": "but still with 1.52",
                "channel_id": "889584618372734977",
                "author": {
                    "id": "440990411591254037",
                    "username": "j_",
                    "avatar": null,
                    "avatar_decoration": null,
                    "discriminator": "2656",
                    "public_flags": 0
                },
                "attachments": [],
                "embeds": [],
                "mentions": [],
                "mention_roles": [],
                "pinned": false,
                "mention_everyone": false,
                "tts": false,
                "timestamp": "2021-10-24T01:07:48.440000+00:00",
                "edited_timestamp": null,
                "flags": 0,
                "components": [],
                "hit": true
            }
        ],
        [
            {
                "id": "901638056522711120",
                "type": 0,
                "content": "what is weird is i then upgraded to 1.56 and this error still appears...",
                "channel_id": "889584618372734977",
                "author": {
                    "id": "440990411591254037",
                    "username": "j_",
                    "avatar": null,
                    "avatar_decoration": null,
                    "discriminator": "2656",
                    "public_flags": 0
                },
                "attachments": [],
                "embeds": [],
                "mentions": [],
                "mention_roles": [],
                "pinned": false,
                "mention_everyone": false,
                "tts": false,
                "timestamp": "2021-10-24T01:07:44.300000+00:00",
                "edited_timestamp": null,
                "flags": 0,
                "components": [],
                "hit": true
            }
        ],
        [
            {
                "id": "901637956534689853",
                "type": 0,
                "content": "",
                "channel_id": "889584618372734977",
                "author": {
                    "id": "440990411591254037",
                    "username": "j_",
                    "avatar": null,
                    "avatar_decoration": null,
                    "discriminator": "2656",
                    "public_flags": 0
                },
                "attachments": [
                    {
                        "id": "901637953091141642",
                        "filename": "unknown.png",
                        "size": 196866,
                        "url": "https://cdn.discordapp.com/attachments/889584618372734977/901637953091141642/unknown.png",
                        "proxy_url": "https://media.discordapp.net/attachments/889584618372734977/901637953091141642/unknown.png",
                        "width": 2720,
                        "height": 756,
                        "content_type": "image/png"
                    }
                ],
                "embeds": [],
                "mentions": [],
                "mention_roles": [],
                "pinned": false,
                "mention_everyone": false,
                "tts": false,
                "timestamp": "2021-10-24T01:07:20.461000+00:00",
                "edited_timestamp": null,
                "flags": 0,
                "components": [],
                "hit": true
            }
        ],
        [
            {
                "id": "901637934090956810",
                "type": 0,
                "content": "Anybody suddenly had this appear? Same code, was compiling earlier, no reason",
                "channel_id": "889584618372734977",
                "author": {
                    "id": "440990411591254037",
                    "username": "j_",
                    "avatar": null,
                    "avatar_decoration": null,
                    "discriminator": "2656",
                    "public_flags": 0
                },
                "attachments": [],
                "embeds": [],
                "mentions": [],
                "mention_roles": [],
                "pinned": false,
                "mention_everyone": false,
                "tts": false,
                "timestamp": "2021-10-24T01:07:15.110000+00:00",
                "edited_timestamp": null,
                "flags": 0,
                "components": [],
                "hit": true
            }
        ]
    ],
    "analytics_id": "ffd6d3ab25583c1c5729bffd6bc82074"
}